"""
OpenAI utilities module.
This module handles interactions with the OpenAI API for generating interview questions.
"""

import os
import openai
from flask import current_app

class OpenAIError(Exception):
    """Base exception class for OpenAI-related errors."""
    pass

class OpenAIKeyError(OpenAIError):
    """Exception raised when OpenAI API key is missing or invalid."""
    pass

class OpenAIRequestError(OpenAIError):
    """Exception raised when OpenAI API request fails."""
    pass

def generate_questions(job_title, job_description, num_questions=5):
    """
    Generate interview questions using OpenAI's API.
    
    Args:
        job_title (str): The title of the job position
        job_description (str): Description of the job requirements and responsibilities
        num_questions (int): Number of questions to generate (default: 5)
        
    Returns:
        list: List of dictionaries containing generated questions and their types
        
    Raises:
        OpenAIKeyError: If OpenAI API key is not configured
        OpenAIRequestError: If API call fails
    """
    # Get OpenAI API key from environment
    api_key = os.getenv('OPENAI_API_KEY')
    if not api_key:
        current_app.logger.warning("OpenAI API key not found. Using fallback questions.")
        return get_fallback_questions(job_title, num_questions)
    
    # Configure OpenAI client
    openai.api_key = api_key
    
    # Create prompt for question generation
    prompt = f"""Generate {num_questions} interview questions for a {job_title} position.
    Job Description: {job_description}
    
    Generate a mix of technical and behavioral questions.
    For each question, specify if it's 'technical' or 'behavioral'.
    Format each question as: 'type: question'
    
    Example:
    technical: What programming languages are you proficient in?
    behavioral: Describe a time when you had to handle a difficult team situation.
    """
    
    try:
        # Call OpenAI API
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are an expert interviewer."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=500
        )
        
        # Parse the response
        content = response.choices[0].message.content
        questions = []
        
        # Split response into lines and process each question
        for line in content.split('\n'):
            if ':' in line:
                q_type, question = line.split(':', 1)
                questions.append({
                    'type': q_type.strip().lower(),
                    'question': question.strip()
                }) 
        
        if not questions:
            current_app.logger.warning("No questions generated by OpenAI. Using fallback questions.")
            return get_fallback_questions(job_title, num_questions)
        
        return questions[:num_questions]  # Ensure we return only the requested number of questions
        
    except openai.error.AuthenticationError as e:
        current_app.logger.error(f"OpenAI authentication error: {str(e)}")
        return get_fallback_questions(job_title, num_questions)
    except openai.error.OpenAIError as e:
        current_app.logger.error(f"OpenAI API error: {str(e)}")
        return get_fallback_questions(job_title, num_questions)
    except Exception as e:
        current_app.logger.error(f"Unexpected error: {str(e)}")
        return get_fallback_questions(job_title, num_questions)

def get_fallback_questions(job_title, num_questions=5):
    """
    Generate fallback questions when OpenAI API is not available.
    
    Args:
        job_title (str): The title of the job position
        num_questions (int): Number of questions to generate
        
    Returns:
        list: List of dictionaries containing generic questions
    """
    # Generic technical and behavioral questions
    technical_questions = [
        "What programming languages are you proficient in?",
        "Describe your experience with databases and data modeling.",
        "How do you approach debugging a complex issue?",
        "Explain your understanding of object-oriented programming principles.",
        "What experience do you have with cloud platforms?",
        "How do you stay updated with the latest technologies?",
        "Describe a challenging technical problem you solved recently.",
        "How do you ensure code quality in your projects?",
        "What's your approach to learning new technologies?",
        "How do you handle technical debt in projects?"
    ]
    
    behavioral_questions = [
        "Tell me about a time when you had to meet a tight deadline.",
        "How do you handle conflicts within a team?",
        "Describe a situation where you had to explain a complex technical concept to non-technical stakeholders.",
        "What's your approach to receiving constructive criticism?",
        "How do you prioritize your work when handling multiple tasks?",
        "Describe a time when you demonstrated leadership skills.",
        "How do you stay motivated during long-term projects?",
        "Tell me about a time when you failed and what you learned from it.",
        "How do you contribute to a positive team culture?",
        "Describe how you've collaborated with people from different backgrounds."
    ]
    
    # Select questions based on job title and required number
    questions = []
    tech_count = num_questions // 2
    behavioral_count = num_questions - tech_count
    
    for i in range(tech_count):
        questions.append({
            'type': 'technical',
            'question': technical_questions[i % len(technical_questions)]
        })
    
    for i in range(behavioral_count):
        questions.append({
            'type': 'behavioral',
            'question': behavioral_questions[i % len(behavioral_questions)]
        })
    
    return questions 